homework 1 ready for check
DmitriyMonarkhov/DmitriiMonarkhov pull request #1
Opened 2022-02-08 14:17 UTC by DmitriyMonarkhov

2022-02-08 15:26 UTC, ZeroShadows requested changes

2022-02-08 15:26 UTC, ZeroShadows commented on src/test/java/hw1/TestingClasses/DivideTest.java
> +        double actual = calculator.div(numb1, numb2);
what will happend if numb2 is 0? let's cover this case to

2022-02-08 15:27 UTC, ZeroShadows commented
general comment - move test classes from folder 'TestClasses' to test folder and remove it

2022-02-09 07:14 UTC, DmitriyMonarkhov commented
Corrections and comments completed

2022-02-10 10:48 UTC, ZeroShadows commented on src/test/java/hw1/dataProviders/DivideDP.java
> +                {34, 0, Double.POSITIVE_INFINITY}
what will happend if it -0? 
Take a look here: https://howtodoinjava.com/testng/testng-expected-exception/

2022-02-10 11:42 UTC, DmitriyMonarkhov commented on src/test/java/hw1/dataProviders/DivideDP.java
> +                {34, 0, Double.POSITIVE_INFINITY}
Thank's! Re-write.

2022-02-10 14:37 UTC, ZeroShadows approved these changes

2022-02-10 14:39 UTC, merged